{
 "title": "taxi data drift",
 "time": { "from": "2023-03-01T00:00:00.000Z", "to": "2023-03-30T00:00:00.000Z" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "description": "features max corr",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", features_max_corr FROM taxi_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Share of missing values",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", share_missing_values FROM taxi_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Number drifted columns",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", num_drifted_columns FROM taxi_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Fare amount 50% quant ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", fare_amount_50quant FROM taxi_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Prediction drift",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", prediction_drift FROM taxi_metrics LIMIT 50 "
    }
   ]
  },
  {
   "type": "welcome",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "type": "gettingstarted",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Dashboards",
   "type": "dashlist",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Latest from the blog",
   "type": "news",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {}
   ]
  }
 ]
}