services:
  # backend:
  #   image: ${LOCAL_IMAGE_NAME}
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - AWS_DEFAULT_REGION=eu-south-1
  #     # - MODEL_LOCATION=/app/model
  #     # - S3_ENDPOINT_URL=http://s3:4566/
  #     - AWS_ACCESS_KEY_ID=test
  #     - AWS_SECRET_ACCESS_KEY=test
  s3:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
